-- =========================================================
-- CHÁ DE PANELA - BANCO SUPABASE
-- Cole TODO este arquivo no SQL Editor do Supabase e execute.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  description text,
  price numeric(10,2) not null check (price >= 0),
  category text not null default 'Casa',
  image_url text,
  store_url text not null,
  status text not null default 'available'
    check (status in ('available', 'reserved', 'confirmed')),
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null unique
    references public.products(id) on delete cascade,
  guest_name text not null check (char_length(guest_name) between 2 and 80),
  method text not null check (method in ('store', 'pix')),
  status text not null default 'reserved'
    check (status in ('reserved', 'confirmed')),
  payment_reported boolean not null default false,
  reservation_token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  confirmed_at timestamptz
);

-- ---------------------------------------------------------
-- RLS
-- ---------------------------------------------------------

alter table public.products enable row level security;
alter table public.reservations enable row level security;

drop policy if exists "public can read products" on public.products;
create policy "public can read products"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "authenticated admins can manage products" on public.products;
create policy "authenticated admins can manage products"
on public.products
for all
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated admins can read reservations" on public.reservations;
create policy "authenticated admins can read reservations"
on public.reservations
for select
to authenticated
using (true);

drop policy if exists "authenticated admins can manage reservations" on public.reservations;
create policy "authenticated admins can manage reservations"
on public.reservations
for all
to authenticated
using (true)
with check (true);

-- Grants explícitos
revoke all on public.products from anon;
revoke all on public.reservations from anon;

grant select on public.products to anon;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.reservations to authenticated;

-- Necessário para o ID automático quando o admin cadastra produto.
grant usage, select on sequence public.products_id_seq to authenticated;

-- ---------------------------------------------------------
-- Função: liberar reservas expiradas
-- O público pode chamar, mas não recebe nomes de convidados.
-- ---------------------------------------------------------

create or replace function public.refresh_expired_reservations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer := 0;
begin
  update public.products p
     set status = 'available'
   where p.status = 'reserved'
     and exists (
       select 1
       from public.reservations r
       where r.product_id = p.id
         and r.status = 'reserved'
         and r.expires_at <= now()
     );

  delete from public.reservations r
   where r.status = 'reserved'
     and r.expires_at <= now();

  get diagnostics affected = row_count;
  return affected;
end;
$$;

-- ---------------------------------------------------------
-- Função: reservar presente
-- Faz lock no produto para impedir duas reservas ao mesmo tempo.
-- ---------------------------------------------------------

create or replace function public.reserve_product(
  p_product_id bigint,
  p_guest_name text,
  p_method text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products%rowtype;
  v_reservation public.reservations%rowtype;
begin
  if p_method not in ('store', 'pix') then
    raise exception 'Forma de presente inválida.';
  end if;

  if p_guest_name is null or char_length(trim(p_guest_name)) < 2 then
    raise exception 'Informe seu nome.';
  end if;

  -- Limpa eventual reserva vencida deste produto.
  delete from public.reservations
   where product_id = p_product_id
     and status = 'reserved'
     and expires_at <= now();

  update public.products
     set status = 'available'
   where id = p_product_id
     and status = 'reserved'
     and not exists (
       select 1 from public.reservations where product_id = p_product_id
     );

  select *
    into v_product
    from public.products
   where id = p_product_id
   for update;

  if not found then
    raise exception 'Presente não encontrado.';
  end if;

  if v_product.status <> 'available' then
    raise exception 'Este presente já foi escolhido por outra pessoa.';
  end if;

  insert into public.reservations (
    product_id,
    guest_name,
    method
  )
  values (
    p_product_id,
    trim(p_guest_name),
    p_method
  )
  returning * into v_reservation;

  update public.products
     set status = 'reserved'
   where id = p_product_id;

  return jsonb_build_object(
    'reservation_token', v_reservation.reservation_token,
    'expires_at', v_reservation.expires_at
  );
end;
$$;

-- ---------------------------------------------------------
-- Loja: convidado informa que concluiu a compra.
-- O token aleatório identifica apenas a própria reserva.
-- ---------------------------------------------------------

create or replace function public.confirm_store_purchase(p_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_id bigint;
begin
  update public.reservations
     set status = 'confirmed',
         confirmed_at = now()
   where reservation_token = p_token
     and method = 'store'
     and status = 'reserved'
     and expires_at > now()
  returning product_id into v_product_id;

  if v_product_id is null then
    raise exception 'Reserva não encontrada ou expirada.';
  end if;

  update public.products
     set status = 'confirmed'
   where id = v_product_id;

  return true;
end;
$$;

-- ---------------------------------------------------------
-- PIX: convidado apenas informa que enviou.
-- O administrador confere no banco e confirma pelo painel.
-- ---------------------------------------------------------

create or replace function public.report_pix_payment(p_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.reservations
     set payment_reported = true
   where reservation_token = p_token
     and method = 'pix'
     and status = 'reserved'
     and expires_at > now();

  if not found then
    raise exception 'Reserva não encontrada ou expirada.';
  end if;

  return true;
end;
$$;

-- ---------------------------------------------------------
-- Admin: confirmar qualquer reserva
-- ---------------------------------------------------------

create or replace function public.admin_confirm_reservation(p_reservation_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_id bigint;
begin
  if auth.role() <> 'authenticated' then
    raise exception 'Não autorizado.';
  end if;

  update public.reservations
     set status = 'confirmed',
         confirmed_at = now()
   where id = p_reservation_id
  returning product_id into v_product_id;

  if v_product_id is null then
    raise exception 'Reserva não encontrada.';
  end if;

  update public.products
     set status = 'confirmed'
   where id = v_product_id;

  return true;
end;
$$;

-- ---------------------------------------------------------
-- Admin: liberar um presente novamente
-- ---------------------------------------------------------

create or replace function public.admin_release_reservation(p_reservation_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product_id bigint;
begin
  if auth.role() <> 'authenticated' then
    raise exception 'Não autorizado.';
  end if;

  select product_id
    into v_product_id
    from public.reservations
   where id = p_reservation_id;

  if v_product_id is null then
    raise exception 'Reserva não encontrada.';
  end if;

  delete from public.reservations
   where id = p_reservation_id;

  update public.products
     set status = 'available'
   where id = v_product_id;

  return true;
end;
$$;

-- ---------------------------------------------------------
-- Permissões das funções
-- ---------------------------------------------------------

revoke all on function public.refresh_expired_reservations() from public;
revoke all on function public.reserve_product(bigint, text, text) from public;
revoke all on function public.confirm_store_purchase(uuid) from public;
revoke all on function public.report_pix_payment(uuid) from public;
revoke all on function public.admin_confirm_reservation(uuid) from public;
revoke all on function public.admin_release_reservation(uuid) from public;

grant execute on function public.refresh_expired_reservations() to anon, authenticated;
grant execute on function public.reserve_product(bigint, text, text) to anon, authenticated;
grant execute on function public.confirm_store_purchase(uuid) to anon, authenticated;
grant execute on function public.report_pix_payment(uuid) to anon, authenticated;

grant execute on function public.admin_confirm_reservation(uuid) to authenticated;
grant execute on function public.admin_release_reservation(uuid) to authenticated;

-- ---------------------------------------------------------
-- Produtos de exemplo. Pode apagar depois.
-- ---------------------------------------------------------

insert into public.products (name, description, price, category, image_url, store_url)
select *
from (
  values
    (
      'Air Fryer',
      'Para os experimentos culinários do nosso futuro lar.',
      399.90,
      'Eletros',
      null,
      'https://www.amazon.com.br/'
    ),
    (
      'Jogo de Panelas',
      'Porque eventualmente vamos ter que cozinhar de verdade. 😂',
      549.90,
      'Cozinha',
      null,
      'https://www.amazon.com.br/'
    ),
    (
      'Liquidificador',
      'Vitaminas, molhos e provavelmente alguma receita que vimos na internet.',
      189.90,
      'Eletros',
      null,
      'https://www.amazon.com.br/'
    )
) as seed(name, description, price, category, image_url, store_url)
where not exists (select 1 from public.products);
